name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 13
      - name: Gradlew
        run: chmod +x ./turbine/gradlew
      - name: build
        run: ./turbine/gradlew build
      - name: cd 
        run: cd ./turbine
      - name: ls
        run: ls
