name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 13
      - name: Gradlew
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
# persistir artefato
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: jar
#          path: build/libs/*.jar
      - name: read and write artifact
        run: chmod -R 777 build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

